name: Build package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v5 # commits the newly built index.js file
        with:
          commit_message: "ci: update index.js"
